project:
  type: website
  output-dir: docs   # this is where the site gets built
    
website:
  title: "My Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-hardesty-6aba092ba?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B4mWdchOGRuaec9X4idasRw%3D%3D

format:
  html:
    theme: architect   # clean, professional
    toc: false



